=== Consumer error strategies

It's possible to define a different error strategy for ann:configuration.kafka.annotation.KafkaListener[] using `errorStrategy` attribute:

.Specifying an error strategy
snippet::io.micronaut.kafka.docs.consumer.errors.StrategyProductListener[tags = annotation, indent = 0]

Setting the error strategy allows you to resume at the next offset or to seek the consumer (stop on error) to the failed offset so that it can retry if an error occurs.

You can choose one of the error strategies:

- `RETRY_ON_ERROR` - This strategy will stop consuming subsequent records in the case of an error and by default will attempt to re-consume the current record once. Possible retry delay can be defined by `retryDelay` and retry count by `retryCount`.

- `RETRY_EXPONENTIALLY_ON_ERROR` - This strategy will stop consuming subsequent records in the case of an error and by default will attempt to re-consume the current record once. The exponentially growing time breaks between consumption attempts is computed using the `n * 2^(k - 1)` formula where the initial delay `n` is `retryDelay` and the number of retries is `retryCount`.

- `RETRY_CONDITIONALLY_ON_ERROR` - This strategy will stop consuming subsequent records in the case of an error and by default will attempt to re-consume the current record once. The retry behaviour can be overridden. Possible retry delay can be defined by `retryDelay` and retry count by `retryCount`.

- `RETRY_CONDITIONALLY_EXPONENTIALLY_ON_ERROR` - This strategy will stop consuming subsequent records in the case of an error and by default will attempt to re-consume the current record once. The retry behaviour can be overridden. The exponentially growing time breaks between consumption attempts is computed using the `n * 2^(k - 1)` formula where the initial delay `n` is `retryDelay` and the number of retries is `retryCount`.

- `RESUME_AT_NEXT_RECORD` - This strategy will ignore the current error and will resume at the next offset, in this case it's recommended to have a custom exception handler that moves the failed message into an error queue.

- `NONE` - This error strategy will skip over all records from the current offset in the current poll when the consumer encounters an error. This option is deprecated and kept for consistent behaviour with previous versions of Micronaut Kafka that do not support error strategy.

NOTE: The error strategies apply only for non-batch messages processing.

NOTE: When using retry error strategies in combination with reactive consumer methods, it is necessary to add the `@Blocking` annotation to the reactive consumer method.

You can also make the number of retries configurable by using `retryCountValue`:

.Dynamically Configuring Retries

snippet::io.micronaut.kafka.docs.consumer.errors.RetryProductListener[tags = annotation, indent = 0]

NOTE: `retryCountValue` will be overridden by `retryCount` if they are both set.

==== Specify exceptions to retry

It's possible to define only exceptions from which the retry will occur.

.Specifying exceptions to retry

snippet::io.micronaut.kafka.docs.consumer.errors.ExceptionProductListener[tags = annotation, indent = 0]

NOTE: Specify exception to retry apply only for `RETRY_ON_ERROR` and `RETRY_EXPONENTIALLY_ON_ERROR` error strategies.

==== Conditional retries

It is possible to conditionally retry a message based on the exception thrown when the error strategy is `RETRY_CONDITIONALLY_ON_ERROR` or `RETRY_CONDITIONALLY_EXPONENTIALLY_ON_ERROR`.

.Specifying conditional retry behaviour on the listener

snippet::io.micronaut.kafka.docs.consumer.errors.ConditionalRetryListener[tags = annotation, indent = 0]

When a ann:configuration.kafka.annotation.KafkaListener[] does not implement ann:configuration.kafka.retry.ConditionalRetryBehaviourHandler[], the ann:configuration.kafka.exceptions.DefaultConditionalRetryBehaviourHandler[] will be used and all messages that failed processing will be retried.

If you wish to apply the same conditional retry strategy for all of your ann:configuration.kafka.annotation.KafkaListener[] you can define a bean that implements `ConditionalRetryBehaviourHandler` and use Micronaut's <<replaces, Bean Replacement>> feature to replace the default bean: `@Replaces(DefaultConditionalRetryBehaviourHandler.class)`.

NOTE: Conditional retry behaviour only applies to `RETRY_CONDITIONALLY_ON_ERROR` and `RETRY_CONDITIONALLY_EXPONENTIALLY_ON_ERROR` error strategies.

=== Exception handlers

When an exception occurs in a ann:configuration.kafka.annotation.KafkaListener[] method by default the exception is simply logged. This is handled by api:configuration.kafka.exceptions.DefaultKafkaListenerExceptionHandler[].

The following options are available to configure the default Kafka listener exception handler:

include::{includedir}configurationProperties/io.micronaut.configuration.kafka.config.DefaultKafkaListenerExceptionHandlerConfigurationProperties.adoc[]

If you wish to replace this default exception handling with another implementation you can use the Micronaut's <<replaces, Bean Replacement>> feature to define a bean that replaces it: `@Replaces(DefaultKafkaListenerExceptionHandler.class)`.

You can also define per bean exception handling logic by implementing the api:configuration.kafka.exceptions.KafkaListenerExceptionHandler[] interface in your ann:configuration.kafka.annotation.KafkaListener[] class.

The api:configuration.kafka.exceptions.KafkaListenerExceptionHandler[] receives an exception of type api:configuration.kafka.exceptions.KafkaListenerException[] which allows access to the original `ConsumerRecord`, if available.
