=== @KafkaListener and Consumer Groups

Kafka consumers created with `@KafkaListener` will by default run within a consumer group that is the value of `micronaut.application.name` unless you explicitly specify a value to the `@KafkaListener` annotation. For example:

.Specifying a Consumer Group

snippet::io.micronaut.kafka.docs.consumer.config.ConsumerGroupListener[tags=annotation, indent=0]

or

.Specifying a Consumer Group alternative

snippet::io.micronaut.kafka.docs.consumer.config.ConsumerGroupIdListener[tags=annotation, indent=0]

The above examples will run the consumer within a consumer group called `myGroup`.
In this case, each record will be consumed by one consumer instance of the consumer group.

TIP: You can make the consumer group configurable using a placeholder: `@KafkaListener("${my.consumer.group:myGroup}")`

To allow the records to be consumed by all the consumer instances (each instance will be part of a unique consumer group), `uniqueGroupId` can be set to `true`:

.Unique group IDs

snippet::io.micronaut.kafka.docs.consumer.config.ConsumerUniqueGroupIdListener[tags=annotation, indent=0]

For more information, see for example https://kafka.apache.org/intro#intro_consumers

=== @KafkaListener and Consumer Properties

There are a number of ways to pass configuration properties to the `KafkaConsumer`. You can set default consumer properties using `kafka.consumers.default` in `application.yml`:

.Applying Default Configuration
[configuration]
----
kafka:
    consumers:
        default:
            session:
                timeout:
                    ms: 30000
----

The above example will set the default `session.timeout.ms` that Kafka uses to decide whether a consumer is alive or not and applies it to all created `KafkaConsumer` instances.

You can also provide configuration specific to a consumer group. For example consider the following configuration:

.Applying Consumer Group Specific config
[configuration]
----
kafka:
    consumers:
        myGroup:
            session:
                timeout:
                    ms: 30000
----

The above configuration will pass properties to only the `@KafkaListener` beans that apply to the consumer group `myGroup`.

Finally, the ann:configuration.kafka.annotation.KafkaListener[] annotation itself provides a `properties` member that you can use to set consumer specific properties:

.Configuring Consumer Properties with @KafkaListener

snippet::io.micronaut.kafka.docs.consumer.config.ProductListener[tags="imports,clazz", indent=0]

=== @KafkaListener and Deserializers

As mentioned previously when defining `@KafkaListener` methods, Micronaut will attempt to pick an appropriate deserializer for the method signature. This is done via the api:configuration.kafka.serde.CompositeSerdeRegistry[] bean.

TIP: You can replace the default api:configuration.kafka.serde.SerdeRegistry[] bean with your own implementation by defining a bean that uses `@Replaces(CompositeSerdeRegistry.class)`. See the section on link:https://docs.micronaut.io/latest/guide/#replaces[Bean Replacement].

All common `java.lang` types (`String`, `Integer`, primitives etc.) are supported and for POJOs by default a Jackson based JSON deserializer is used.

You can, however, explicitly override the `Deserializer` used by providing the appropriate configuration in `application.yml`:

.Applying Default Configuration
[configuration]
----
kafka:
    consumers:
        myGroup:
            value:
                deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
----

You may want to do this if for example you choose an alternative deserialization format such as Avro or Protobuf.

=== Transactional properties

There are a few options that can be enabled for only in the transactional processing:

==== Isolation

Use `isolation` member to define if you want to receive messages that haven't been committed yet.

==== Custom offset strategy

There is a special offset strategy `OffsetStrategy.SEND_TO_TRANSACTION` that can only be used with an associated producer, only applicable when `SendTo` is used.
