https://kafka.apache.org[Apache Kafka] is a distributed stream processing platform that can be used for a range of messaging requirements in addition to stream processing and real-time data handling.

Micronaut features dedicated support for defining both Kafka `Producer` and `Consumer` instances. Micronaut applications built with Kafka can be deployed with or without the presence of an HTTP server.

With Micronaut's efficient compile-time AOP and cloud native features, writing efficient Kafka consumer applications that use very little resources is a breeze.

=== Release History

==== 1.3.0

* Upgrade to Kafka 2.3.1
* Micronaut 1.2.x Minimum Version

==== 1.2.0

* Upgrade to Kafka 2.3.0
* Micronaut 1.1.x Minimum Version

==== 1.1.0

* Upgrade to Kafka 2.1.0

==== 1.0.4

* Upgrade to Kafka 2.0.1

==== 1.1.0

* Upgrade to Kafka 2.1.1
* Support for Open Tracing
* Support for Pausing / Resuming Consumers via api:configuration.kafka.ConsumerRegistry[] interface

==== 1.2.0

* Micronaut 1.1.x minimum version
* Upgrade to Kafka 2.3.0
* GraalVM Native Support (with Micronaut 1.2+)
* Better Exception Handling
