The quick start section presented a trivial example of what is possible with the ann:configuration.kafka.annotation.KafkaListener[] annotation.

Using the `@KafkaListener` annotation Micronaut will build a link:{kafkaapi}/org/apache/kafka/clients/consumer/KafkaConsumer.html[KafkaConsumer] and start the `poll` loop by running the `KafkaConsumer` in a special `consumer` thread pool. You can configure the size of the thread pool based on the number of consumers in your application in `application.yml` as desired:

.Configuring the `consumer` thread pool
[configuration]
----
micronaut:
    executors:
        consumer:
            type: fixed
            nThreads: 25
----

`KafkaConsumer` instances are single threaded, hence for each `@KafkaListener` method you define a new thread is created to execute the `poll` loop.

You may wish to scale the number of consumers you have listening on a particular topic. There are several ways you may achieve this. You could for example run multiple instances of your application each containing a single consumer in each JVM.

Alternatively, you can also scale via threads. By setting the number of `threads` a particular consumer bean will create:

.Scaling with Threads

snippet::io.micronaut.kafka.docs.consumer.threads.ScalingThreadsListener[tags="annotation", indent=0]

The above example will create 10 link:{kafkaapi}/org/apache/kafka/clients/consumer/KafkaConsumer.html[KafkaConsumer] instances, each running in a unique thread and participating in the `myGroup` consumer group.

NOTE: @KafkaListener beans are by default singleton. When using multiple threads you must either synchronize access to local state or declare the bean as `@Prototype`.

You can also make your number of threads configurable by using `threadsValue`:

.Dynamically Configuring Threads

snippet::io.micronaut.kafka.docs.consumer.threads.DynamicThreadsListener[tags="annotation", indent=0]

NOTE: `threads` will be overridden by `threadsValue` if they are both set.

By default Micronaut will inspect the method signature of the method annotated with `@Topic` that will listen for `ConsumerRecord` instances and from the types infer an appropriate key and value link:{kafkaapi}/org/apache/kafka/common/serialization/Deserializer.html[Deserializer].

.Applying Configuration
[configuration]
----
kafka:
    consumers:
        default:
            allow.auto.create.topics: true
        product:
            bootstrap:
              servers: localhost:9098
----

Properties under `kafka.consumers.default` serve as shared defaults applied to all link:{kafkaapi}/org/apache/kafka/clients/consumer/ConsumerConfig.html[ConsumerConfig]-compatible consumers, while properties under `kafka.consumers.<id>` apply only to the consumer whose `id` matches (falling back to `groupId` when `id` is not set). The above example enables topic auto-creation for all consumers via the `default` key and sets a custom bootstrap server only for a listener declared with `@KafkaListener(id = "product")`.

TIP: See the guide for https://guides.micronaut.io/latest/testing-micronaut-kafka-listener-using-testcontainers.html[Testing Kafka Listener using Testcontainers with the Micronaut Framework] to learn more.
