To create a project with Kafka support using the Micronaut CLI, supply the `kafka` feature to the `features` flag.

----
$ mn create-app my-kafka-app --features kafka
----

This will create a project with the minimum necessary configuration for Kafka.

== Kafka Messaging Application

The Micronaut CLI includes the ability to create Kafka-based messaging applications designed to implement message-driven microservices. 

To create a Message-Driven Microservice with Micronaut + Kafka use the `create-messaging-app` command:

----
$ mn create-messaging-app my-kafka-app --features kafka
----

As you'd expect, you can start the application with `./gradlew run` (for Gradle) or `./mvnw compile exec:exec` (Maven). The application will (with the default config) attempt to connect to Kafka at `http://localhost:9092`, and will continue to run without starting up an HTTP server. All communication to/from the service will take place via Kafka producers and/or listeners.

Within the new project, you can now run the Kafka-specific code generation commands:

----
$ mn create-kafka-producer MessageProducer
| Rendered template Producer.java to destination src/main/java/my/kafka/app/MessageProducer.java

$ mn create-kafka-listener MessageListener
| Rendered template Listener.java to destination src/main/java/my/kafka/app/MessageListener.java
----
