[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `kafka-streams` feature to include a simple Kafka Streams configuration in your project:
----
$ mn create-app my-app --features kafka-streams
----
====

https://kafka.apache.org/documentation/streams/[Kafka Streams] is a platform for building real time streaming applications.

When using Micronaut with Kafka Stream, your application gains all of the features from Micronaut (configuration management, AOP, DI, health checks etc.), simplifying the construction of Kafka Stream applications.

Since Micronaut's DI and AOP is compile time, you can build low overhead stream applications with ease.

== Defining Kafka Streams

To define Kafka Streams you should first add the `kafka-streams` configuration to your build.

dependency:micronaut-kafka-streams[groupId="io.micronaut.kafka"]

The minimum configuration required is to set the Kafka bootstrap servers:

.Configuring Kafka
[source,yaml]
----
kafka:
    bootstrap:
        servers: localhost:9092
----


You should then define a ann:context.annotation.Factory[] for your streams that defines beans that return a `KStream`. For example to implement the Word Count example from the Kafka Streams documentation:

.Kafka Streams Word Count

snippet::io.micronaut.kafka.docs.streams.WordCountStream[tags="imports, clazz, wordCountStream"]

<1> An instance of api:configuration.kafka.streams.ConfiguredStreamBuilder[] is injected that allows mutating the configuration
<2> The input topic
<3> Materialize the count stream and save to a state store
<4> The output topic

NOTE: With Kafka streams the key and value `Serdes` (serializer/deserializer) must be classes with a zero argument constructor. If you wish to use JSON (de)serialization you can subclass api:configuration.kafka.serde.JsonObjectSerde[] to define your `Serdes`

You can use the ann:configuration.kafka.annotation.KafkaClient[] annotation to send a sentence to be processed by the above stream:

.Defining a Kafka Client

snippet::io.micronaut.kafka.docs.streams.WordCountClient[tags="imports, clazz", indent=0]

You can also define a ann:configuration.kafka.annotation.KafkaListener[] to listen for the result of the word count stream:

.Defining a Kafka Listener

snippet::io.micronaut.kafka.docs.streams.WordCountListener[tags="imports, clazz", indent=0]

== Configuring Kafka Streams

.Configuring a single Stream on a Micronaut application.
If you have a single Kafka Stream configured on your Micronaut service, then you should use the `default` key on the configuration.

[source,yaml]
----
kafka:
    streams:
       default:
          processing.guarantee: "exactly_once"
          auto.offset.reset: "earliest"
----

The above configuration example sets the `processing.guarantee` and `auto.offset.reset` setting of the `default` Stream.

.Configuring multiple Stream definitions on the same Micronaut Service.
You can define multiple Kafka Streams on the same Micronaut application, each with their own unique configuration.
To do this you should define the configuration with `kafka.streams.[STREAM-NAME]`.
Assuming you have 2 or more Kafka Streams definitions on a single service, you will need to use the `default` key for at least one of them and then define `kafka.streams.[STREAM-NAME]` for the rest.

For example in `application.yml`:

[source,yaml]
----
kafka:
    streams:
        default:
          num:
            stream:
              threads: 1
        my-other-stream:
          num:
            stream:
              threads: 10
----

The above configuration sets the `num.stream.threads` setting of the Kafka `StreamsConfig` to `1` for the `default` stream, and the same setting to `10` for a stream named `my-stream`.

You can then inject an `api:configuration.kafka.streams.ConfiguredStreamBuilder[]` specifically for the above configuration using `jakarta.inject.Named`:

snippet::io.micronaut.kafka.docs.streams.WordCountStream[tags="clazz, myOtherStream"]

NOTE: If you do not provide a `@Named` on the `ConfiguredStreamBuilder` you have multiple KStreams defined that share the default configurations like client id, application id, etc.It is advisable when using multiple streams in a single app to provide a `@Named` instance of `ConfiguredStreamBuilder` for each stream.

.Kafka Streams Word Count

snippet::io.micronaut.kafka.docs.streams.WordCountStream[tags="clazz, namedStream"]

.Configuring Kafka Streams for testing
When writing a test without starting the actual Kafka server, you can instruct Micronaut not to start Kafka Streams. To do this create a config file suffixed with an environment name, such as `application-test.yml` and set the `kafka.streams.[STREAM-NAME].start-kafka-streams` to `false`.


For example in `application-test.yml`:

[source,yaml]
----
kafka:
    streams:
        default:
            start-kafka-streams: false
----
