plugins {
    id 'io.micronaut.build.internal.kafka-base'
}

tasks.withType(Test) {
    useJUnitPlatform()
}

dependencies {
    testImplementation projects.micronautKafka
    testImplementation projects.micronautKafkaStreams

    testImplementation mn.micronaut.messaging
    testImplementation mnSerde.micronaut.serde.jackson
    testImplementation mnReactor.micronaut.reactor
    testImplementation mnSerde.micronaut.serde.jackson
    testImplementation(project(":test-suite-utils"))
    testImplementation libs.awaitility

    testRuntimeOnly mnLogging.logback.classic
    testRuntimeOnly(mnTest.junit.platform.launcher)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
}

micronaut {
    importMicronautPlatform.set(false)
}
