plugins {
    id 'io.micronaut.build.internal.module'
    id 'io.micronaut.build.internal.kafka-base'
}

dependencies {
    api mn.micronaut.messaging
    api mn.micronaut.json.core

    compileOnly mn.micronaut.management

    implementation mn.reactor

    testAnnotationProcessor mn.micronaut.inject.java

    testImplementation mnMicrometer.micronaut.micrometer.core
    testImplementation mn.micronaut.management

    testRuntimeOnly mnCache.micronaut.cache.core
    testRuntimeOnly mnReactor.micronaut.reactor
    testRuntimeOnly mn.micronaut.http.server.netty
    testRuntimeOnly mn.micronaut.management
    testRuntimeOnly mn.snakeyaml
}

configurations.all {
    resolutionStrategy {
        force 'org.graalvm.sdk:graal-sdk:25.0.1'
    }
}

test {
    maxHeapSize = '2048m'
}

ossIndexAudit {
    excludeCoordinates = [
            "org.lz4:lz4-java:1.8.0" // no version patched https://ossindex.sonatype.org/vulnerability/CVE-2025-12183?component-type=maven&component-name=org.lz4%2Flz4-java&utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.2
    ]
}
