plugins {
    id 'io.micronaut.build.internal.kafka-tests'
}

application {
    mainClass = 'example.Application'
}

dependencies {
    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.testcontainers.kafka)
    testImplementation(projects.testSuiteKafkaUtils)
}

tasks.named("internalStartTestResourcesService") {
    setProperty("useClassDataSharing", false)
}
