[versions]
micronaut = "5.0.2"
micronaut-platform = "5.0.2"
micronaut-gradle-plugin = "5.0.0"
micronaut-test = "5.0.1"

# Required to keep catalog compatibility with 3.4.x.  Can be removed for 4.0.0
managed-kafka = '4.2.0'

awaitility = '4.3.0'
opentracing-kafka-client = '0.1.15'
opentracing-mock = '0.33.0'

zipkin-brave-kafka-clients = '6.3.1'

micronaut-cache = "6.0.0"
micronaut-micrometer = "6.0.0"
micronaut-reactor = "4.0.0"
micronaut-serde = "3.0.0"
micronaut-tracing = "8.0.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-kafka-clients = { module = 'org.apache.kafka:kafka-clients', version.ref = 'managed-kafka' }
managed-kafka-streams = { module = 'org.apache.kafka:kafka-streams', version.ref = 'managed-kafka' }

opentracing-kafka-client = { module = 'io.opentracing.contrib:opentracing-kafka-client', version.ref = 'opentracing-kafka-client' }
opentracing-mock = { module = 'io.opentracing:opentracing-mock', version.ref = 'opentracing-mock' }

zipkin-brave-kafka-clients = { module = 'io.zipkin.brave:brave-instrumentation-kafka-clients', version.ref = 'zipkin-brave-kafka-clients' }
awaitility = { module = 'org.awaitility:awaitility', version.ref = 'awaitility' }

micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-tracing = { module = "io.micronaut.tracing:micronaut-tracing-bom", version.ref = "micronaut-tracing" }
micronaut-test = { module = "io.micronaut.test:micronaut-test-bom", version.ref = "micronaut-test" }
testcontainers = { module = "org.testcontainers:testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka" }
micronaut-gradle-plugin = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

[plugins]
