plugins {
    id 'io.micronaut.build.internal.kafka-module'
}

configurations.all {
    resolutionStrategy {
        force 'io.micronaut.platform:micronaut-platform:5.1.5'
    }
}



dependencies {
    api projects.micronautKafka
    api libs.managed.kafka.streams
    compileOnly mnSerde.micronaut.serde.api
    compileOnly mnMicrometer.micronaut.micrometer.core
    testImplementation mn.micronaut.http.client
    testImplementation mnSerde.micronaut.serde.jackson
    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.testcontainers.kafka)
}
