plugins {
    id 'io.micronaut.build.internal.kafka-module'
}

configurations.all {
    resolutionStrategy {
        force 'io.micronaut.platform:micronaut-platform:4.10.3'
    }
}



dependencies {
    api projects.micronautKafka
    api libs.managed.kafka.streams
    compileOnly mnSerde.micronaut.serde.api
    compileOnly mnMicrometer.micronaut.micrometer.core
    testImplementation mn.micronaut.http.client
    testImplementation mnSerde.micronaut.serde.jackson
    implementation(platform(mnTest.boms.testcontainers))
}
