Transaction processing can be enabled by defining `transactionalId` on `@KafkaClient`, which will initialize the producer for transactional usage and wrap any send operation with a transaction demarcation.

.Transactional Client

snippet::io.micronaut.kafka.docs.producer.config.TransactionalClient[tags = 'clazz']

Alternatively, the same transaction demarcation can be done by hand with an injected transactional `Producer` (see <<kafkaClientScope,Injecting Kafka Producer Beans>>):

.Alternative Kafka producer transactional code

snippet::io.micronaut.kafka.docs.producer.config.TransactionalProducer[tags = 'clazz']

<1> The injected `Producer` is already initialized for transactions, so `initTransactions()` must not be called again
<2> Every `send` operation is wrapped in a transaction
<3> The transaction is committed once the records are sent
<4> The transaction is aborted if sending fails

[NOTE]
====
`@KafkaClient` beans are by default singleton. When using multiple threads, you must either synchronize access to the individual instance or declare the bean as `@Prototype`. Additionally, you can use link:https://docs.micronaut.io/latest/guide/#_using_random_properties[random properties] to your advantage so that each instance of your producer gets a different transactional ID.

.Random transactional ID

snippet::io.micronaut.kafka.docs.producer.config.RandomTransactionalIdClient[tags = 'clazz']
====
