Transaction processing can be enabled by defining `transactionalId` on `@KafkaClient`, which will initialize the producer for transactional usage and wrap any send operation with a transaction demarcation.

.Transactional Client

snippet::io.micronaut.kafka.docs.producer.config.TransactionalClient[tags = 'clazz']

.Alternative Kafka producer transactional code
[source,java]
----
producer.initTransactions();
try {
    producer.beginTransaction();
    producer.send(...);
    producer.commitTransaction();
} catch (Exception e) {
    producer.abortTransaction();
}
----

[NOTE]
====
`@KafkaClient` beans are by default singleton. When using multiple threads, you must either synchronize access to the individual instance or declare the bean as `@Prototype`. Additionally, you can use link:https://docs.micronaut.io/latest/guide/#_using_random_properties[random properties] to your advantage so that each instance of your producer gets a different transactional ID.

.Random transactional ID

snippet::io.micronaut.kafka.docs.producer.config.RandomTransactionalIdClient[tags = 'clazz']
====
