plugins {
    id 'io.micronaut.build.internal.kafka-module'
}

configurations.all {
    resolutionStrategy {
        force 'org.graalvm.sdk:graal-sdk:25.0.3'
        force 'io.micronaut.platform:micronaut-platform:5.0.2'
    }
}


dependencies {
    annotationProcessor mn.micronaut.graal

    api(libs.managed.kafka.clients) {
        exclude(group: "com.fasterxml.jackson.core", module: "jackson-core")
    }
    constraints {
        // "org.apache.kafka:kafka-clients 4.2.0 requests jackson-core 2.19.1, which is affected by GHSA-72hv-8253-57qq"
        api("com.fasterxml.jackson.core:jackson-core:2.21.1") {
            because("Require a non-vulnerable jackson-core version instead of the transitive 2.19.1 from :kafka-clients")
        }
    }
    api("com.fasterxml.jackson.core:jackson-core")

    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.testcontainers.kafka)
    compileOnly mnMicrometer.micronaut.micrometer.core
    compileOnly mnMicrometer.micronaut.micrometer.registry.prometheus
    compileOnly libs.zipkin.brave.kafka.clients
    compileOnly mn.micronaut.graal

    testImplementation mnSerde.micronaut.serde.jackson
    testImplementation(mnReactor.micronaut.reactor)
    testImplementation mn.micronaut.http.client
    testImplementation mnMicrometer.micronaut.micrometer.registry.prometheus
    testImplementation(projects.testSuiteKafkaUtils)
    testImplementation(mnTest.junit.jupiter.api)
    testImplementation libs.awaitility

    testRuntimeOnly mnMicrometer.micronaut.micrometer.registry.statsd
    testRuntimeOnly mnTracing.micronaut.tracing.core
    testRuntimeOnly(mnTest.junit.jupiter.engine)
}
